import Head from 'next/head';
import Image from 'next/image';
import Topbar from '../components/topBar';
import styles from '../styles/Home.module.css';
import Container from '@mui/material/Container';
import Box from '@mui/material/Box';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Welcome to June's Work!</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Topbar />
        <Container maxWidth="sm">
          <h1>
            Hi, I'm June
          </h1>
          <div>

          </div>          
        </Container>

      </main>

      <footer className={styles.footer}>

      </footer>
    </div>
  )
}
